### ISSUE TITLE
Cannot read documentElement of undefined

### ISSUE THREAD

**Issue by IanDavey** [Xcential-Corporation/XSLTjs#13]
I run the following:
```js
'use strict';

const fs = require('fs');
const { XSLT } = require('xsltjs');

const inputXML = fs.readFileSync('s70505.uslm');

XSLT.transform({
  source: inputXML.toString(),
  xsltPath: 'USLM_to_HTML.xsl',
  result: String,
  params: {
    docTitle: '51 U.S.C. 70505',
    identifier: '/us/usc/t51/s70505'
  }
}, (err, result) => {
  if (err) throw new Error(err);
  else fs.writeFileSync('transformed.html', result);
});
```
I get:
```
(node:5904) UnhandledPromiseRejectionWarning: Error: TypeError: Cannot read property 'documentElement' of undefined
    at C:\inetpub\LRCResolver\xsltjstest.js:17:18
    at C:\inetpub\LRCResolver\node_modules\xsltjs\scripts\XSLT.js:171:18
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing insi
de of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs
.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5904) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections
 that are not handled will terminate the Node.js process with a non-zero exit code.
```
This is XSLTjs `0.0.38`, Node `14.15.1`, the input XML from `http://olrc.xcential.com/uslm/us/usc/t51/s70505.uslm`, and the transform from the [USLM develop branch](https://github.com/Xcential-Corporation/USLM/blob/4d3f18a6fa6dda278c97f3fb2b2d15fe01934983/transforms/USLM_to_HTML.xsl)

**Comment by IanDavey** [comment]
FWIW, replacing the `xsltPath` line with `xslt: fs.readFileSync('USLM_to_HTML.xsl').toString(),` works.
